const accounts = ["Northstar Labs", "Acme Systems", "Pioneer Telecom"];

export default function DashboardInsights() {
  return (
    <section className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
      <div className="panel p-6"><div className="flex items-center justify-between"><h3 className="text-lg font-semibold text-slate-900">Churn trend</h3><span className="text-xs text-slate-500">Last 6 months</span></div><div className="mt-6 flex h-36 items-end gap-3">{[42, 55, 48, 68, 57, 72].map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-lg bg-gradient-to-t from-indigo-600 to-blue-400" style={{ height: `${height}%` }} /><span className="text-[11px] text-slate-400">M{index + 1}</span></div>)}</div></div>
      <div className="panel p-6"><div className="flex items-center justify-between"><h3 className="text-lg font-semibold text-slate-900">Churn by segment</h3><span className="text-xs text-slate-500">Current mix</span></div><div className="mt-6 flex items-center gap-6"><div className="h-28 w-28 rounded-full bg-[conic-gradient(#4f46e5_0_42%,#14b8a6_42%_70%,#f59e0b_70%_88%,#e2e8f0_88%)] p-5"><div className="flex h-full items-center justify-center rounded-full bg-white text-sm font-bold text-slate-900">42%</div></div><div className="space-y-2 text-xs text-slate-600"><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-indigo-600" />Month-to-month</p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-teal-500" />One year</p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-amber-500" />Two year</p></div></div></div>
      <div className="panel p-6 lg:col-span-2"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 className="text-lg font-semibold text-slate-900">At-risk customers</h3><p className="mt-1 text-sm text-slate-500">Prioritize accounts that need a human touch.</p></div><input className="field max-w-xs" placeholder="Search customers" aria-label="Search customers" /></div><div className="mt-5 divide-y divide-slate-100">{accounts.map((account, index) => <div key={account} className="flex items-center justify-between gap-4 py-3 text-sm"><span className="flex items-center gap-3 font-medium text-slate-800"><i className={`h-2.5 w-2.5 rounded-full ${index === 0 ? "bg-rose-500" : index === 1 ? "bg-amber-400" : "bg-emerald-500"}`} />{account}</span><span className="text-slate-500">{index === 0 ? "High risk" : index === 1 ? "Watch" : "Healthy"}</span></div>)}</div></div>
    </section>
  );
}
